name: .NET

on: [workflow_dispatch]

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Git version tag
      id: version
      run: |
        echo "::set-output name=tag::`echo $(git describe --tags --abbrev=0)`"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x
          6.0.x
          
    - name: Update package version
      shell: pwsh
      run: |
        $commitCount = git rev-list --count $env:GITHUB_REF
        $packageVersion = (Select-Xml -Path ./src/Directory.Build.props -XPath '/Project/PropertyGroup/PackageVersion').Node.InnerXML
        "ASSEMBLY_VERSION={0}" -f ($packageVersion -replace '^(.*)\.\d+.*$', "`$1.$commitCount.0") >> $env:GITHUB_ENV
        "PACKAGE_VERSION={0}" -f ($packageVersion -replace '^(.*)\.\d+.*$', "`$1.$commitCount") >> $env:GITHUB_ENV

    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
      
    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release -p:Version=${{ env.PACKAGE_VERSION }} -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} -p:FileVersion=${{ env.ASSEMBLY_VERSION }}
      
    - name: Test
      working-directory: ./src
      run: dotnet test --configuration Release --no-build --verbosity normal --filter Category!=Integration
      
    - name: Pack
      working-directory: ./src
      run: dotnet pack --configuration Release --no-build -p:Version=${{ env.PACKAGE_VERSION }} -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:ProjectUrl=https://github.com/${{ github.repository }} -p:RepositoryUrl=https://github.com/${{ github.repository }}

    - name: Push
      working-directory: ./src
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
        dotnet nuget push **/bin/Release/*.nupkg --source "github" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
        dotnet nuget push **/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_ORG_API_KEY }}
